"""add efiboot option

Revision ID: 138919866e75
Revises: ffa897d733ca
Create Date: 2018-04-07 11:45:17.506953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138919866e75'
down_revision = 'ffa897d733ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subarch', sa.Column('efiboot', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subarch', 'efiboot')
    # ### end Alembic commands ###
