"""machine events

Revision ID: 203f6105a16b
Revises: 5ff7c035ac37
Create Date: 2018-02-08 04:05:47.857990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '203f6105a16b'
down_revision = '5ff7c035ac37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('info', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('console_token', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'console_token', 'machine', ['machine_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'console_token', type_='foreignkey')
    op.drop_column('console_token', 'machine_id')
    op.drop_table('machine_event')
    # ### end Alembic commands ###
