"""Add state to machine

Revision ID: 25be6fb1804a
Revises: 12d9fa9e4227
Create Date: 2017-09-07 19:38:31.271403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25be6fb1804a'
down_revision = '12d9fa9e4227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'state')
    # ### end Alembic commands ###
