"""Adding name to networks

Revision ID: 2961f5fa1383
Revises: 5f6ebd17bbd0
Create Date: 2017-06-29 17:13:49.727849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2961f5fa1383'
down_revision = '5f6ebd17bbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('name', sa.String(), nullable=False))
    op.execute('UPDATE network SET name=subnet')
    op.create_unique_constraint(None, 'network', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'network', type_='unique')
    op.drop_column('network', 'name')
    # ### end Alembic commands ###
