"""differentiate static vs rsvd ipv4

Revision ID: 5f6ebd17bbd0
Revises: 9b3f2d2b2de6
Create Date: 2017-06-27 18:47:47.475126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6ebd17bbd0'
down_revision = '9b3f2d2b2de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interface', sa.Column('reserved_ipv4', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'interface', ['reserved_ipv4'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interface', type_='unique')
    op.drop_column('interface', 'reserved_ipv4')
    # ### end Alembic commands ###
