"""add interfaces & leases

Revision ID: 7636dd6850b8
Revises: b3f287936412
Create Date: 2017-06-18 06:55:04.886049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7636dd6850b8'
down_revision = 'b3f287936412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac')
    )
    op.create_table('interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('dhcpv4', sa.Boolean(), nullable=True),
    sa.Column('static_ipv4', sa.String(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac'),
    sa.UniqueConstraint('static_ipv4')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interface')
    op.drop_table('lease')
    # ### end Alembic commands ###
