"""constraint improvements

Revision ID: 8fed83f88b6b
Revises: 2961f5fa1383
Create Date: 2017-07-08 07:26:58.254966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fed83f88b6b'
down_revision = '2961f5fa1383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('interface_reserved_ipv4_key', 'interface', type_='unique')
    op.drop_constraint('interface_static_ipv4_key', 'interface', type_='unique')
    op.create_unique_constraint(None, 'interface', ['static_ipv4', 'network_id'])
    op.create_unique_constraint(None, 'interface', ['reserved_ipv4', 'network_id'])
    op.create_unique_constraint(None, 'machine_users', ['machine_id', 'user_id'])
    op.alter_column('preseed', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preseed', 'file_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('preseed_description_key', 'preseed', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('preseed_description_key', 'preseed', ['description'])
    op.alter_column('preseed', 'file_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('preseed', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'machine_users', type_='unique')
    op.drop_constraint(None, 'interface', type_='unique')
    op.drop_constraint(None, 'interface', type_='unique')
    op.create_unique_constraint('interface_static_ipv4_key', 'interface', ['static_ipv4'])
    op.create_unique_constraint('interface_reserved_ipv4_key', 'interface', ['reserved_ipv4'])
    op.alter_column('image', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
