"""add new network table

Revision ID: 9b3f2d2b2de6
Revises: 546f8e248b7e
Create Date: 2017-06-27 18:20:17.798199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3f2d2b2de6'
down_revision = '546f8e248b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subnet', sa.String(), nullable=False),
    sa.Column('reserved_net', sa.String(), nullable=True),
    sa.Column('static_net', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserved_net'),
    sa.UniqueConstraint('static_net'),
    sa.UniqueConstraint('subnet')
    )
    op.add_column('interface', sa.Column('network_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interface', 'network', ['network_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interface', type_='foreignkey')
    op.drop_column('interface', 'network_id')
    op.drop_table('network')
    # ### end Alembic commands ###
