"""console user_id

Revision ID: ffa897d733ca
Revises: 203f6105a16b
Create Date: 2018-02-15 19:51:24.274921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa897d733ca'
down_revision = '203f6105a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('console_token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'console_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'console_token', type_='foreignkey')
    op.drop_column('console_token', 'user_id')
    # ### end Alembic commands ###
